### PR TITLE
[14.0][MIG] mass and donation_mass

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Comment by rafaelbn** [comment]
Travis 🔴

**Comment by alexis-via** [comment]
Let's see if Travis is green now...

**Comment by alexis-via** [comment]
I hope travis will turn green this time...

**Comment by alexis-via** [comment]
Travis is green at last ! Better late than never!

**Comment by alexis-via** [comment]
seems the OCA bot is asleep...

**Pull request merged**
